/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.calculator_app;

import java.awt.ComponentOrientation;

/**
 *
 * @author konri
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        this.setTitle("Calculator");
        this.setLocationRelativeTo(null);
        smallResultTextPane.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);   
        resultTextPane.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainFrame = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        modeLabel = new javax.swing.JLabel();
        modeTitleLabel = new javax.swing.JLabel();
        outputPanel = new javax.swing.JPanel();
        smallOutputPanel = new javax.swing.JPanel();
        leftScrollButton = new javax.swing.JButton();
        rightScrollButton = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        smallResultTextPane = new javax.swing.JTextPane();
        resultTextPane = new javax.swing.JTextPane();
        memoryButtonPanel = new javax.swing.JPanel();
        clearMemoryButton = new javax.swing.JButton();
        recallMemoryButton = new javax.swing.JButton();
        addMemoryButton = new javax.swing.JButton();
        subtractMemoryButton = new javax.swing.JButton();
        storeMemoryButton = new javax.swing.JButton();
        memoryButton = new javax.swing.JButton();
        mainButtonPanel = new javax.swing.JPanel();
        percentageButton = new javax.swing.JButton();
        clearEntryButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        backspaceButton = new javax.swing.JButton();
        fractionButton = new javax.swing.JButton();
        squaredButton = new javax.swing.JButton();
        squareRootButton = new javax.swing.JButton();
        divisionButton = new javax.swing.JButton();
        number7Button = new javax.swing.JButton();
        number8Button = new javax.swing.JButton();
        number9Button = new javax.swing.JButton();
        multiplicationButton = new javax.swing.JButton();
        number4Button = new javax.swing.JButton();
        number5Button = new javax.swing.JButton();
        number6Button = new javax.swing.JButton();
        subtractionButton = new javax.swing.JButton();
        number1Button = new javax.swing.JButton();
        number2Button = new javax.swing.JButton();
        number3Button = new javax.swing.JButton();
        additionButton = new javax.swing.JButton();
        positiveNegativeButton = new javax.swing.JButton();
        number0Button = new javax.swing.JButton();
        decimalButton = new javax.swing.JButton();
        equalButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(335, 510));
        setPreferredSize(new java.awt.Dimension(335, 510));

        mainFrame.setBackground(new java.awt.Color(230, 230, 230));
        mainFrame.setPreferredSize(new java.awt.Dimension(0, 0));

        topPanel.setBackground(new java.awt.Color(102, 102, 255));
        topPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        topPanel.setPreferredSize(new java.awt.Dimension(0, 36));

        String mode = new String("\u2630").toUpperCase();
        modeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N
        modeLabel.setToolTipText("Open Navigation");
        modeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modeLabel.setBounds(2, 6, 61, 37);

        modeTitleLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        modeTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        modeTitleLabel.setText("Standard");
        modeTitleLabel.setMaximumSize(new java.awt.Dimension(75, 24));
        modeTitleLabel.setMinimumSize(new java.awt.Dimension(75, 24));
        modeTitleLabel.setPreferredSize(new java.awt.Dimension(75, 24));

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modeLabel)
                .addGap(18, 18, 18)
                .addComponent(modeTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modeTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        outputPanel.setBackground(new java.awt.Color(255, 102, 102));

        smallOutputPanel.setLayout(new java.awt.GridBagLayout());

        leftScrollButton.setBackground(new java.awt.Color(230, 230, 230));
        leftScrollButton.setBorder(null);
        leftScrollButton.setFocusPainted(false);
        leftScrollButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        leftScrollButton.setMaximumSize(new java.awt.Dimension(18, 17));
        leftScrollButton.setMinimumSize(new java.awt.Dimension(18, 17));
        leftScrollButton.setPreferredSize(new java.awt.Dimension(18, 17));
        leftScrollButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                leftScrollButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                leftScrollButtonMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        smallOutputPanel.add(leftScrollButton, gridBagConstraints);

        rightScrollButton.setBackground(new java.awt.Color(230, 230, 230));
        rightScrollButton.setBorder(null);
        rightScrollButton.setFocusPainted(false);
        rightScrollButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        rightScrollButton.setMaximumSize(new java.awt.Dimension(18, 17));
        rightScrollButton.setMinimumSize(new java.awt.Dimension(18, 17));
        rightScrollButton.setPreferredSize(new java.awt.Dimension(18, 17));
        rightScrollButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rightScrollButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rightScrollButtonMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        smallOutputPanel.add(rightScrollButton, gridBagConstraints);

        jScrollPane.setBorder(null);
        jScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        smallResultTextPane.setBackground(new java.awt.Color(230, 230, 230));
        smallResultTextPane.setBorder(null);
        smallResultTextPane.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        smallResultTextPane.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jScrollPane.setViewportView(smallResultTextPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        smallOutputPanel.add(jScrollPane, gridBagConstraints);

        resultTextPane.setBorder(null);
        resultTextPane.setFont(new java.awt.Font("Segoe UI Semibold", 1, 45)); // NOI18N
        resultTextPane.setForeground(new java.awt.Color(0, 0, 0));
        resultTextPane.setText("0");
        resultTextPane.setMargin(new java.awt.Insets(0, 10, 5, 10));

        javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
        outputPanel.setLayout(outputPanelLayout);
        outputPanelLayout.setHorizontalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(smallOutputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultTextPane)
                .addContainerGap())
        );
        outputPanelLayout.setVerticalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(smallOutputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(resultTextPane, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        memoryButtonPanel.setBackground(new java.awt.Color(230, 230, 230));
        memoryButtonPanel.setPreferredSize(new java.awt.Dimension(0, 28));
        memoryButtonPanel.setLayout(new java.awt.GridLayout(1, 6, 2, 0));

        clearMemoryButton.setBackground(new java.awt.Color(230, 230, 230));
        clearMemoryButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        clearMemoryButton.setForeground(new java.awt.Color(0, 0, 0));
        clearMemoryButton.setText("MC");
        clearMemoryButton.setToolTipText("");
        clearMemoryButton.setBorder(null);
        clearMemoryButton.setEnabled(false);
        clearMemoryButton.setFocusPainted(false);
        clearMemoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMemoryButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMemoryButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMemoryButtonMouseExited(evt);
            }
        });
        memoryButtonPanel.add(clearMemoryButton);

        recallMemoryButton.setBackground(new java.awt.Color(230, 230, 230));
        recallMemoryButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        recallMemoryButton.setForeground(new java.awt.Color(0, 0, 0));
        recallMemoryButton.setText("MR");
        recallMemoryButton.setToolTipText("");
        recallMemoryButton.setBorder(null);
        recallMemoryButton.setEnabled(false);
        recallMemoryButton.setFocusPainted(false);
        recallMemoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recallMemoryButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recallMemoryButtonMouseExited(evt);
            }
        });
        memoryButtonPanel.add(recallMemoryButton);

        addMemoryButton.setBackground(new java.awt.Color(230, 230, 230));
        addMemoryButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        addMemoryButton.setForeground(new java.awt.Color(0, 0, 0));
        addMemoryButton.setText("M+");
        addMemoryButton.setToolTipText("Memory add");
        addMemoryButton.setBorder(null);
        addMemoryButton.setFocusPainted(false);
        addMemoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMemoryButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMemoryButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMemoryButtonMouseExited(evt);
            }
        });
        memoryButtonPanel.add(addMemoryButton);

        subtractMemoryButton.setBackground(new java.awt.Color(230, 230, 230));
        subtractMemoryButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        subtractMemoryButton.setForeground(new java.awt.Color(0, 0, 0));
        subtractMemoryButton.setText("M-");
        subtractMemoryButton.setToolTipText("Memory subtrack");
        subtractMemoryButton.setBorder(null);
        subtractMemoryButton.setFocusPainted(false);
        subtractMemoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subtractMemoryButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subtractMemoryButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subtractMemoryButtonMouseExited(evt);
            }
        });
        memoryButtonPanel.add(subtractMemoryButton);

        storeMemoryButton.setBackground(new java.awt.Color(230, 230, 230));
        storeMemoryButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        storeMemoryButton.setForeground(new java.awt.Color(0, 0, 0));
        storeMemoryButton.setText("MS");
        storeMemoryButton.setToolTipText("Memory store");
        storeMemoryButton.setBorder(null);
        storeMemoryButton.setFocusPainted(false);
        storeMemoryButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        storeMemoryButton.setIconTextGap(0);
        storeMemoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                storeMemoryButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                storeMemoryButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                storeMemoryButtonMouseExited(evt);
            }
        });
        memoryButtonPanel.add(storeMemoryButton);

        memoryButton.setBackground(new java.awt.Color(230, 230, 230));
        memoryButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        memoryButton.setForeground(new java.awt.Color(0, 0, 0));
        memoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black-triangle-down-10x10.png"))); // NOI18N
        memoryButton.setText("M");
        memoryButton.setToolTipText("");
        memoryButton.setBorder(null);
        memoryButton.setEnabled(false);
        memoryButton.setFocusPainted(false);
        memoryButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        memoryButton.setIconTextGap(0);
        memoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                memoryButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                memoryButtonMouseExited(evt);
            }
        });
        memoryButtonPanel.add(memoryButton);

        mainButtonPanel.setBackground(new java.awt.Color(230, 230, 230));
        mainButtonPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        mainButtonPanel.setLayout(new java.awt.GridLayout(6, 4, 2, 2));

        percentageButton.setBackground(new java.awt.Color(240, 240, 240));
        percentageButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        percentageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-percentage-20.png"))); // NOI18N
        percentageButton.setBorder(null);
        percentageButton.setBorderPainted(false);
        percentageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                percentageButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                percentageButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(percentageButton);

        clearEntryButton.setBackground(new java.awt.Color(240, 240, 240));
        clearEntryButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        clearEntryButton.setForeground(new java.awt.Color(65, 65, 64));
        clearEntryButton.setText("CE");
        clearEntryButton.setBorder(null);
        clearEntryButton.setBorderPainted(false);
        clearEntryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearEntryButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearEntryButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(clearEntryButton);

        clearButton.setBackground(new java.awt.Color(240, 240, 240));
        clearButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        clearButton.setForeground(new java.awt.Color(65, 65, 64));
        clearButton.setText("C");
        clearButton.setBorder(null);
        clearButton.setBorderPainted(false);
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(clearButton);

        backspaceButton.setBackground(new java.awt.Color(240, 240, 240));
        backspaceButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        backspaceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-backspace-20.png"))); // NOI18N
        backspaceButton.setBorder(null);
        backspaceButton.setBorderPainted(false);
        backspaceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backspaceButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backspaceButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(backspaceButton);

        fractionButton.setBackground(new java.awt.Color(240, 240, 240));
        fractionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oie_58tr4EM4IOKH.png"))); // NOI18N
        fractionButton.setBorder(null);
        fractionButton.setBorderPainted(false);
        fractionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fractionButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fractionButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(fractionButton);

        squaredButton.setBackground(new java.awt.Color(240, 240, 240));
        squaredButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x-square.png"))); // NOI18N
        squaredButton.setBorder(null);
        squaredButton.setBorderPainted(false);
        squaredButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                squaredButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                squaredButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(squaredButton);

        squareRootButton.setBackground(new java.awt.Color(240, 240, 240));
        squareRootButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/square-root-2.png"))); // NOI18N
        squareRootButton.setBorder(null);
        squareRootButton.setBorderPainted(false);
        squareRootButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                squareRootButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                squareRootButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(squareRootButton);

        divisionButton.setBackground(new java.awt.Color(240, 240, 240));
        divisionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-divide-20-less.png"))); // NOI18N
        divisionButton.setBorder(null);
        divisionButton.setBorderPainted(false);
        divisionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                divisionButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                divisionButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(divisionButton);

        number7Button.setBackground(new java.awt.Color(249, 249, 249));
        number7Button.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        number7Button.setForeground(new java.awt.Color(0, 0, 0));
        number7Button.setText("7");
        number7Button.setBorder(null);
        number7Button.setBorderPainted(false);
        number7Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                number7ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                number7ButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(number7Button);

        number8Button.setBackground(new java.awt.Color(249, 249, 249));
        number8Button.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        number8Button.setForeground(new java.awt.Color(0, 0, 0));
        number8Button.setText("8");
        number8Button.setBorder(null);
        number8Button.setBorderPainted(false);
        number8Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                number8ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                number8ButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(number8Button);

        number9Button.setBackground(new java.awt.Color(249, 249, 249));
        number9Button.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        number9Button.setForeground(new java.awt.Color(0, 0, 0));
        number9Button.setText("9");
        number9Button.setBorder(null);
        number9Button.setBorderPainted(false);
        number9Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                number9ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                number9ButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(number9Button);

        multiplicationButton.setBackground(new java.awt.Color(240, 240, 240));
        multiplicationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-multiply-20b.png"))); // NOI18N
        multiplicationButton.setBorder(null);
        multiplicationButton.setBorderPainted(false);
        multiplicationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                multiplicationButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                multiplicationButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(multiplicationButton);

        number4Button.setBackground(new java.awt.Color(249, 249, 249));
        number4Button.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        number4Button.setForeground(new java.awt.Color(0, 0, 0));
        number4Button.setText("4");
        number4Button.setBorder(null);
        number4Button.setBorderPainted(false);
        number4Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                number4ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                number4ButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(number4Button);

        number5Button.setBackground(new java.awt.Color(249, 249, 249));
        number5Button.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        number5Button.setForeground(new java.awt.Color(0, 0, 0));
        number5Button.setText("5");
        number5Button.setBorder(null);
        number5Button.setBorderPainted(false);
        number5Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                number5ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                number5ButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(number5Button);

        number6Button.setBackground(new java.awt.Color(249, 249, 249));
        number6Button.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        number6Button.setForeground(new java.awt.Color(0, 0, 0));
        number6Button.setText("6");
        number6Button.setBorder(null);
        number6Button.setBorderPainted(false);
        number6Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                number6ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                number6ButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(number6Button);

        subtractionButton.setBackground(new java.awt.Color(240, 240, 240));
        subtractionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-subtract-20-black.png"))); // NOI18N
        subtractionButton.setBorder(null);
        subtractionButton.setBorderPainted(false);
        subtractionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subtractionButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subtractionButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(subtractionButton);

        number1Button.setBackground(new java.awt.Color(249, 249, 249));
        number1Button.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        number1Button.setForeground(new java.awt.Color(0, 0, 0));
        number1Button.setText("1");
        number1Button.setBorder(null);
        number1Button.setBorderPainted(false);
        number1Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                number1ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                number1ButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(number1Button);

        number2Button.setBackground(new java.awt.Color(249, 249, 249));
        number2Button.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        number2Button.setForeground(new java.awt.Color(0, 0, 0));
        number2Button.setText("2");
        number2Button.setBorder(null);
        number2Button.setBorderPainted(false);
        number2Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                number2ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                number2ButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(number2Button);

        number3Button.setBackground(new java.awt.Color(249, 249, 249));
        number3Button.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        number3Button.setForeground(new java.awt.Color(0, 0, 0));
        number3Button.setText("3");
        number3Button.setBorder(null);
        number3Button.setBorderPainted(false);
        number3Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                number3ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                number3ButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(number3Button);

        additionButton.setBackground(new java.awt.Color(240, 240, 240));
        additionButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        additionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-plus-math-20.png"))); // NOI18N
        additionButton.setBorder(null);
        additionButton.setBorderPainted(false);
        additionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                additionButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                additionButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(additionButton);

        positiveNegativeButton.setBackground(new java.awt.Color(249, 249, 249));
        positiveNegativeButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        positiveNegativeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-plus-slash-minus-20.png"))); // NOI18N
        positiveNegativeButton.setBorder(null);
        positiveNegativeButton.setBorderPainted(false);
        positiveNegativeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                positiveNegativeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                positiveNegativeButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(positiveNegativeButton);

        number0Button.setBackground(new java.awt.Color(249, 249, 249));
        number0Button.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        number0Button.setForeground(new java.awt.Color(0, 0, 0));
        number0Button.setText("0");
        number0Button.setBorder(null);
        number0Button.setBorderPainted(false);
        number0Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                number0ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                number0ButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(number0Button);

        decimalButton.setBackground(new java.awt.Color(249, 249, 249));
        decimalButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        decimalButton.setText(",");
        decimalButton.setBorder(null);
        decimalButton.setBorderPainted(false);
        decimalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                decimalButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                decimalButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(decimalButton);

        equalButton.setBackground(new java.awt.Color(236, 177, 142));
        equalButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-equal-sign-20.png"))); // NOI18N
        equalButton.setBorder(null);
        equalButton.setBorderPainted(false);
        equalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                equalButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                equalButtonMouseExited(evt);
            }
        });
        mainButtonPanel.add(equalButton);

        javax.swing.GroupLayout mainFrameLayout = new javax.swing.GroupLayout(mainFrame);
        mainFrame.setLayout(mainFrameLayout);
        mainFrameLayout.setHorizontalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
            .addComponent(outputPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(memoryButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
            .addGroup(mainFrameLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(mainButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );
        mainFrameLayout.setVerticalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainFrameLayout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(outputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(memoryButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(mainButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void percentageButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_percentageButtonMouseEntered
        percentageButton.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_percentageButtonMouseEntered

    private void percentageButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_percentageButtonMouseExited
        percentageButton.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_percentageButtonMouseExited

    private void clearEntryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearEntryButtonMouseEntered
        clearEntryButton.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_clearEntryButtonMouseEntered

    private void clearEntryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearEntryButtonMouseExited
        clearEntryButton.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_clearEntryButtonMouseExited

    private void clearButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseEntered
        clearButton.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_clearButtonMouseEntered

    private void clearButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseExited
        clearButton.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_clearButtonMouseExited

    private void backspaceButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backspaceButtonMouseEntered
        backspaceButton.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_backspaceButtonMouseEntered

    private void backspaceButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backspaceButtonMouseExited
        backspaceButton.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_backspaceButtonMouseExited

    private void fractionButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fractionButtonMouseEntered
        fractionButton.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_fractionButtonMouseEntered

    private void fractionButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fractionButtonMouseExited
        fractionButton.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_fractionButtonMouseExited

    private void squaredButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_squaredButtonMouseEntered
        squaredButton.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_squaredButtonMouseEntered

    private void squaredButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_squaredButtonMouseExited
        squaredButton.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_squaredButtonMouseExited

    private void squareRootButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_squareRootButtonMouseEntered
        squareRootButton.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_squareRootButtonMouseEntered

    private void squareRootButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_squareRootButtonMouseExited
        squareRootButton.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_squareRootButtonMouseExited

    private void divisionButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisionButtonMouseEntered
        divisionButton.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_divisionButtonMouseEntered

    private void divisionButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisionButtonMouseExited
       divisionButton.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_divisionButtonMouseExited

    private void multiplicationButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicationButtonMouseEntered
        multiplicationButton.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_multiplicationButtonMouseEntered

    private void multiplicationButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicationButtonMouseExited
        multiplicationButton.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_multiplicationButtonMouseExited

    private void subtractionButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtractionButtonMouseEntered
        subtractionButton.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_subtractionButtonMouseEntered

    private void subtractionButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtractionButtonMouseExited
        subtractionButton.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_subtractionButtonMouseExited

    private void additionButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_additionButtonMouseEntered
        additionButton.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_additionButtonMouseEntered

    private void additionButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_additionButtonMouseExited
        additionButton.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_additionButtonMouseExited

    private void number7ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number7ButtonMouseEntered
        number7Button.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_number7ButtonMouseEntered

    private void number7ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number7ButtonMouseExited
        number7Button.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_number7ButtonMouseExited

    private void number8ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number8ButtonMouseEntered
        number8Button.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_number8ButtonMouseEntered

    private void number8ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number8ButtonMouseExited
        number8Button.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_number8ButtonMouseExited

    private void number9ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number9ButtonMouseEntered
        number9Button.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_number9ButtonMouseEntered

    private void number9ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number9ButtonMouseExited
        number9Button.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_number9ButtonMouseExited

    private void number4ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number4ButtonMouseEntered
        number4Button.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_number4ButtonMouseEntered

    private void number4ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number4ButtonMouseExited
        number4Button.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_number4ButtonMouseExited

    private void number5ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number5ButtonMouseEntered
        number5Button.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_number5ButtonMouseEntered

    private void number5ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number5ButtonMouseExited
        number5Button.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_number5ButtonMouseExited

    private void number6ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number6ButtonMouseEntered
        number6Button.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_number6ButtonMouseEntered

    private void number6ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number6ButtonMouseExited
        number6Button.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_number6ButtonMouseExited

    private void number1ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number1ButtonMouseEntered
        number1Button.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_number1ButtonMouseEntered

    private void number1ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number1ButtonMouseExited
        number1Button.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_number1ButtonMouseExited

    private void number2ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number2ButtonMouseEntered
        number2Button.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_number2ButtonMouseEntered

    private void number2ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number2ButtonMouseExited
        number2Button.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_number2ButtonMouseExited

    private void number3ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number3ButtonMouseEntered
        number3Button.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_number3ButtonMouseEntered

    private void number3ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number3ButtonMouseExited
        number3Button.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_number3ButtonMouseExited

    private void positiveNegativeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_positiveNegativeButtonMouseEntered
        positiveNegativeButton.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_positiveNegativeButtonMouseEntered

    private void positiveNegativeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_positiveNegativeButtonMouseExited
        positiveNegativeButton.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_positiveNegativeButtonMouseExited

    private void number0ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number0ButtonMouseEntered
        number0Button.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_number0ButtonMouseEntered

    private void number0ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number0ButtonMouseExited
        number0Button.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_number0ButtonMouseExited

    private void decimalButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decimalButtonMouseEntered
        decimalButton.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_decimalButtonMouseEntered

    private void decimalButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decimalButtonMouseExited
        decimalButton.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_decimalButtonMouseExited

    private void equalButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalButtonMouseEntered
        equalButton.setBackground(new java.awt.Color(241,138,77));
    }//GEN-LAST:event_equalButtonMouseEntered

    private void equalButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalButtonMouseExited
        equalButton.setBackground(new java.awt.Color(236,177,142));
    }//GEN-LAST:event_equalButtonMouseExited

    private void clearMemoryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMemoryButtonMouseEntered
        if(clearMemoryButton.isEnabled()){
            clearMemoryButton.setBackground(new java.awt.Color(209,209,209));
            clearMemoryButton.setToolTipText("Clear all memory");
        }
    }//GEN-LAST:event_clearMemoryButtonMouseEntered

    private void clearMemoryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMemoryButtonMouseExited
        clearMemoryButton.setBackground(new java.awt.Color(230,230,230));
    }//GEN-LAST:event_clearMemoryButtonMouseExited

    private void recallMemoryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recallMemoryButtonMouseEntered
        if(recallMemoryButton.isEnabled()){
            recallMemoryButton.setBackground(new java.awt.Color(209,209,209));
            recallMemoryButton.setToolTipText("Memory recall");
        }
    }//GEN-LAST:event_recallMemoryButtonMouseEntered

    private void recallMemoryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recallMemoryButtonMouseExited
        recallMemoryButton.setBackground(new java.awt.Color(230,230,230));
    }//GEN-LAST:event_recallMemoryButtonMouseExited

    private void addMemoryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMemoryButtonMouseEntered
        addMemoryButton.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_addMemoryButtonMouseEntered

    private void addMemoryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMemoryButtonMouseExited
       addMemoryButton.setBackground(new java.awt.Color(230,230,230));
    }//GEN-LAST:event_addMemoryButtonMouseExited

    private void subtractMemoryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtractMemoryButtonMouseEntered
        subtractMemoryButton.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_subtractMemoryButtonMouseEntered

    private void subtractMemoryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtractMemoryButtonMouseExited
        subtractMemoryButton.setBackground(new java.awt.Color(230,230,230));
    }//GEN-LAST:event_subtractMemoryButtonMouseExited

    private void storeMemoryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storeMemoryButtonMouseEntered
        storeMemoryButton.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_storeMemoryButtonMouseEntered

    private void storeMemoryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storeMemoryButtonMouseExited
       storeMemoryButton.setBackground(new java.awt.Color(230,230,230));
    }//GEN-LAST:event_storeMemoryButtonMouseExited

    private void memoryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memoryButtonMouseEntered
       if(memoryButton.isEnabled()){
           memoryButton.setBackground(new java.awt.Color(209,209,209));
           memoryButton.setToolTipText("Memory");
       }
    }//GEN-LAST:event_memoryButtonMouseEntered

    private void memoryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memoryButtonMouseExited
        memoryButton.setBackground(new java.awt.Color(230,230,230));
    }//GEN-LAST:event_memoryButtonMouseExited

    private void addMemoryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMemoryButtonMouseClicked
        clearMemoryButton.setEnabled(true);
        recallMemoryButton.setEnabled(true);
        memoryButton.setEnabled(true);
    }//GEN-LAST:event_addMemoryButtonMouseClicked

    private void subtractMemoryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtractMemoryButtonMouseClicked
        clearMemoryButton.setEnabled(true);
        recallMemoryButton.setEnabled(true);
        memoryButton.setEnabled(true);
    }//GEN-LAST:event_subtractMemoryButtonMouseClicked

    private void storeMemoryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storeMemoryButtonMouseClicked
        clearMemoryButton.setEnabled(true);
        recallMemoryButton.setEnabled(true);
        memoryButton.setEnabled(true);
    }//GEN-LAST:event_storeMemoryButtonMouseClicked

    private void clearMemoryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMemoryButtonMouseClicked
        if(clearMemoryButton.isEnabled()){
            clearMemoryButton.setEnabled(false);
            recallMemoryButton.setEnabled(false);
            memoryButton.setEnabled(false);
        }
    }//GEN-LAST:event_clearMemoryButtonMouseClicked

    private void leftScrollButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftScrollButtonMouseEntered
        if (smallResultTextPane.getText().equals("")) {
            leftScrollButtonDisable();
        } else {
            leftScrollButtonEnableFocused();
        }
    }//GEN-LAST:event_leftScrollButtonMouseEntered

    private void leftScrollButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftScrollButtonMouseExited
        if (smallResultTextPane.getText().equals("")) {
            leftScrollButtonDisable();
        } else {
            leftScrollButtonEnableUnfocused();
        }
    }//GEN-LAST:event_leftScrollButtonMouseExited

    private void rightScrollButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightScrollButtonMouseEntered
        if (smallResultTextPane.getText().equals("")) {
            rightScrollButtonDisable();
        } else {
            rightScrollButtonEnableFocused();
        }
    }//GEN-LAST:event_rightScrollButtonMouseEntered

    private void rightScrollButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightScrollButtonMouseExited
        if (smallResultTextPane.getText().equals("")) {
            rightScrollButtonDisable();
        } else {
            rightScrollButtonEnableUnfocused();
        }
    }//GEN-LAST:event_rightScrollButtonMouseExited

    private void leftScrollButtonEnableUnfocused() {
        leftScrollButton.setEnabled(true);
        leftScrollButton.setBackground(new java.awt.Color(209,209,209));
        leftScrollButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-less-than-15-orange.png")));
    }

    private void leftScrollButtonEnableFocused() {
        leftScrollButton.setEnabled(true);
        leftScrollButton.setBackground(new java.awt.Color(209,209,209));
        leftScrollButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-less-than-15-black.png")));
    }

    private void leftScrollButtonDisable() {
        leftScrollButton.setEnabled(false);
        leftScrollButton.setBackground(new java.awt.Color(230,230,230));
        leftScrollButton.setIcon(null);
    }

    private void rightScrollButtonDisable() {
        rightScrollButton.setEnabled(false);
        rightScrollButton.setBackground(new java.awt.Color(230,230,230));
        rightScrollButton.setIcon(null);
    }

    private void rightScrollButtonEnableUnfocused() {
        rightScrollButton.setEnabled(true);
        rightScrollButton.setBackground(new java.awt.Color(209,209,209));
        rightScrollButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-more-than-15-orange.png")));
    }

    private void rightScrollButtonEnableFocused() {
        rightScrollButton.setEnabled(true);
        rightScrollButton.setBackground(new java.awt.Color(209,209,209));
        rightScrollButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-more-than-15-black.png")));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMemoryButton;
    private javax.swing.JButton additionButton;
    private javax.swing.JButton backspaceButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton clearEntryButton;
    private javax.swing.JButton clearMemoryButton;
    private javax.swing.JButton decimalButton;
    private javax.swing.JButton divisionButton;
    private javax.swing.JButton equalButton;
    private javax.swing.JButton fractionButton;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JButton leftScrollButton;
    private javax.swing.JPanel mainButtonPanel;
    private javax.swing.JPanel mainFrame;
    private javax.swing.JButton memoryButton;
    private javax.swing.JPanel memoryButtonPanel;
    private javax.swing.JLabel modeLabel;
    private javax.swing.JLabel modeTitleLabel;
    private javax.swing.JButton multiplicationButton;
    private javax.swing.JButton number0Button;
    private javax.swing.JButton number1Button;
    private javax.swing.JButton number2Button;
    private javax.swing.JButton number3Button;
    private javax.swing.JButton number4Button;
    private javax.swing.JButton number5Button;
    private javax.swing.JButton number6Button;
    private javax.swing.JButton number7Button;
    private javax.swing.JButton number8Button;
    private javax.swing.JButton number9Button;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JButton percentageButton;
    private javax.swing.JButton positiveNegativeButton;
    private javax.swing.JButton recallMemoryButton;
    private javax.swing.JTextPane resultTextPane;
    private javax.swing.JButton rightScrollButton;
    private javax.swing.JPanel smallOutputPanel;
    private javax.swing.JTextPane smallResultTextPane;
    private javax.swing.JButton squareRootButton;
    private javax.swing.JButton squaredButton;
    private javax.swing.JButton storeMemoryButton;
    private javax.swing.JButton subtractMemoryButton;
    private javax.swing.JButton subtractionButton;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
