/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.calculator_app;

/**
 *
 * @author konri
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        this.setTitle("Calculator");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        modelLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        outputPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        clearMemoryButton = new javax.swing.JButton();
        recallMemoryButton = new javax.swing.JButton();
        addMemoryButton = new javax.swing.JButton();
        subtrackMemoryButton = new javax.swing.JButton();
        storeMemoryButton = new javax.swing.JButton();
        memoryButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(335, 510));
        setPreferredSize(new java.awt.Dimension(335, 509));

        jPanel1.setBackground(new java.awt.Color(230, 230, 230));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));

        TopPanel.setBackground(new java.awt.Color(102, 102, 255));
        TopPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        TopPanel.setPreferredSize(new java.awt.Dimension(0, 36));

        String mode = new String("\u2630").toUpperCase();
        modelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N
        modelLabel.setToolTipText("Open Navigation");
        modelLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modelLabel.setBounds(2, 6, 61, 37);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Standard");
        jLabel1.setMaximumSize(new java.awt.Dimension(75, 24));
        jLabel1.setMinimumSize(new java.awt.Dimension(75, 24));
        jLabel1.setPreferredSize(new java.awt.Dimension(75, 24));

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modelLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        outputPanel.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
        outputPanel.setLayout(outputPanelLayout);
        outputPanelLayout.setHorizontalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        outputPanelLayout.setVerticalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(230, 230, 230));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 28));
        jPanel2.setLayout(new java.awt.GridLayout(1, 6, 2, 0));

        clearMemoryButton.setBackground(new java.awt.Color(230, 230, 230));
        clearMemoryButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        clearMemoryButton.setForeground(new java.awt.Color(0, 0, 0));
        clearMemoryButton.setText("MC");
        clearMemoryButton.setToolTipText("");
        clearMemoryButton.setBorder(null);
        clearMemoryButton.setEnabled(false);
        clearMemoryButton.setFocusPainted(false);
        clearMemoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMemoryButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMemoryButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMemoryButtonMouseExited(evt);
            }
        });
        jPanel2.add(clearMemoryButton);

        recallMemoryButton.setBackground(new java.awt.Color(230, 230, 230));
        recallMemoryButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        recallMemoryButton.setForeground(new java.awt.Color(0, 0, 0));
        recallMemoryButton.setText("MR");
        recallMemoryButton.setToolTipText("");
        recallMemoryButton.setBorder(null);
        recallMemoryButton.setEnabled(false);
        recallMemoryButton.setFocusPainted(false);
        recallMemoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recallMemoryButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recallMemoryButtonMouseExited(evt);
            }
        });
        jPanel2.add(recallMemoryButton);

        addMemoryButton.setBackground(new java.awt.Color(230, 230, 230));
        addMemoryButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        addMemoryButton.setForeground(new java.awt.Color(0, 0, 0));
        addMemoryButton.setText("M+");
        addMemoryButton.setToolTipText("Memory add");
        addMemoryButton.setBorder(null);
        addMemoryButton.setFocusPainted(false);
        addMemoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMemoryButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMemoryButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMemoryButtonMouseExited(evt);
            }
        });
        jPanel2.add(addMemoryButton);

        subtrackMemoryButton.setBackground(new java.awt.Color(230, 230, 230));
        subtrackMemoryButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        subtrackMemoryButton.setForeground(new java.awt.Color(0, 0, 0));
        subtrackMemoryButton.setText("M-");
        subtrackMemoryButton.setToolTipText("Memory subtrack");
        subtrackMemoryButton.setBorder(null);
        subtrackMemoryButton.setFocusPainted(false);
        subtrackMemoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subtrackMemoryButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subtrackMemoryButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subtrackMemoryButtonMouseExited(evt);
            }
        });
        jPanel2.add(subtrackMemoryButton);

        storeMemoryButton.setBackground(new java.awt.Color(230, 230, 230));
        storeMemoryButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        storeMemoryButton.setForeground(new java.awt.Color(0, 0, 0));
        storeMemoryButton.setText("MS");
        storeMemoryButton.setToolTipText("Memory store");
        storeMemoryButton.setBorder(null);
        storeMemoryButton.setFocusPainted(false);
        storeMemoryButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        storeMemoryButton.setIconTextGap(0);
        storeMemoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                storeMemoryButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                storeMemoryButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                storeMemoryButtonMouseExited(evt);
            }
        });
        jPanel2.add(storeMemoryButton);

        memoryButton.setBackground(new java.awt.Color(230, 230, 230));
        memoryButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        memoryButton.setForeground(new java.awt.Color(0, 0, 0));
        memoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black-triangle-down-10x10.png"))); // NOI18N
        memoryButton.setText("M");
        memoryButton.setToolTipText("");
        memoryButton.setBorder(null);
        memoryButton.setEnabled(false);
        memoryButton.setFocusPainted(false);
        memoryButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        memoryButton.setIconTextGap(0);
        memoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                memoryButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                memoryButtonMouseExited(evt);
            }
        });
        jPanel2.add(memoryButton);

        mainPanel.setBackground(new java.awt.Color(230, 230, 230));
        mainPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        mainPanel.setLayout(new java.awt.GridLayout(6, 4, 2, 2));

        jButton1.setBackground(new java.awt.Color(240, 240, 240));
        jButton1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-percentage-20.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        mainPanel.add(jButton1);

        jButton3.setBackground(new java.awt.Color(240, 240, 240));
        jButton3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(65, 65, 64));
        jButton3.setText("CE");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        mainPanel.add(jButton3);

        jButton4.setBackground(new java.awt.Color(240, 240, 240));
        jButton4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(65, 65, 64));
        jButton4.setText("C");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        mainPanel.add(jButton4);

        jButton5.setBackground(new java.awt.Color(240, 240, 240));
        jButton5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-backspace-20.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        mainPanel.add(jButton5);

        jButton6.setBackground(new java.awt.Color(240, 240, 240));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oie_58tr4EM4IOKH.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        mainPanel.add(jButton6);

        jButton7.setBackground(new java.awt.Color(240, 240, 240));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x-square.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7MouseExited(evt);
            }
        });
        mainPanel.add(jButton7);

        jButton8.setBackground(new java.awt.Color(240, 240, 240));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/square-root-2.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton8MouseExited(evt);
            }
        });
        mainPanel.add(jButton8);

        jButton17.setBackground(new java.awt.Color(240, 240, 240));
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-divide-20-less.png"))); // NOI18N
        jButton17.setBorder(null);
        jButton17.setBorderPainted(false);
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton17MouseExited(evt);
            }
        });
        mainPanel.add(jButton17);

        jButton18.setBackground(new java.awt.Color(249, 249, 249));
        jButton18.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton18.setForeground(new java.awt.Color(0, 0, 0));
        jButton18.setText("7");
        jButton18.setBorder(null);
        jButton18.setBorderPainted(false);
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton18MouseExited(evt);
            }
        });
        mainPanel.add(jButton18);

        jButton34.setBackground(new java.awt.Color(249, 249, 249));
        jButton34.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton34.setForeground(new java.awt.Color(0, 0, 0));
        jButton34.setText("8");
        jButton34.setBorder(null);
        jButton34.setBorderPainted(false);
        jButton34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton34MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton34MouseExited(evt);
            }
        });
        mainPanel.add(jButton34);

        jButton32.setBackground(new java.awt.Color(249, 249, 249));
        jButton32.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton32.setForeground(new java.awt.Color(0, 0, 0));
        jButton32.setText("9");
        jButton32.setBorder(null);
        jButton32.setBorderPainted(false);
        jButton32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton32MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton32MouseExited(evt);
            }
        });
        mainPanel.add(jButton32);

        jButton13.setBackground(new java.awt.Color(240, 240, 240));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-multiply-20b.png"))); // NOI18N
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton13MouseExited(evt);
            }
        });
        mainPanel.add(jButton13);

        jButton26.setBackground(new java.awt.Color(249, 249, 249));
        jButton26.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton26.setForeground(new java.awt.Color(0, 0, 0));
        jButton26.setText("4");
        jButton26.setBorder(null);
        jButton26.setBorderPainted(false);
        jButton26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton26MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton26MouseExited(evt);
            }
        });
        mainPanel.add(jButton26);

        jButton27.setBackground(new java.awt.Color(249, 249, 249));
        jButton27.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton27.setForeground(new java.awt.Color(0, 0, 0));
        jButton27.setText("5");
        jButton27.setBorder(null);
        jButton27.setBorderPainted(false);
        jButton27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton27MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton27MouseExited(evt);
            }
        });
        mainPanel.add(jButton27);

        jButton28.setBackground(new java.awt.Color(249, 249, 249));
        jButton28.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton28.setForeground(new java.awt.Color(0, 0, 0));
        jButton28.setText("6");
        jButton28.setBorder(null);
        jButton28.setBorderPainted(false);
        jButton28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton28MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton28MouseExited(evt);
            }
        });
        mainPanel.add(jButton28);

        jButton9.setBackground(new java.awt.Color(240, 240, 240));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-subtract-20-black.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton9MouseExited(evt);
            }
        });
        mainPanel.add(jButton9);

        jButton29.setBackground(new java.awt.Color(249, 249, 249));
        jButton29.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton29.setForeground(new java.awt.Color(0, 0, 0));
        jButton29.setText("1");
        jButton29.setBorder(null);
        jButton29.setBorderPainted(false);
        jButton29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton29MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton29MouseExited(evt);
            }
        });
        mainPanel.add(jButton29);

        jButton30.setBackground(new java.awt.Color(249, 249, 249));
        jButton30.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton30.setForeground(new java.awt.Color(0, 0, 0));
        jButton30.setText("2");
        jButton30.setBorder(null);
        jButton30.setBorderPainted(false);
        jButton30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton30MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton30MouseExited(evt);
            }
        });
        mainPanel.add(jButton30);

        jButton31.setBackground(new java.awt.Color(249, 249, 249));
        jButton31.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton31.setForeground(new java.awt.Color(0, 0, 0));
        jButton31.setText("3");
        jButton31.setBorder(null);
        jButton31.setBorderPainted(false);
        jButton31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton31MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton31MouseExited(evt);
            }
        });
        mainPanel.add(jButton31);

        jButton25.setBackground(new java.awt.Color(240, 240, 240));
        jButton25.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-plus-math-20.png"))); // NOI18N
        jButton25.setBorder(null);
        jButton25.setBorderPainted(false);
        jButton25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton25MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton25MouseExited(evt);
            }
        });
        mainPanel.add(jButton25);

        jButton22.setBackground(new java.awt.Color(249, 249, 249));
        jButton22.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-plus-slash-minus-20.png"))); // NOI18N
        jButton22.setBorder(null);
        jButton22.setBorderPainted(false);
        jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton22MouseExited(evt);
            }
        });
        mainPanel.add(jButton22);

        jButton33.setBackground(new java.awt.Color(249, 249, 249));
        jButton33.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton33.setForeground(new java.awt.Color(0, 0, 0));
        jButton33.setText("0");
        jButton33.setBorder(null);
        jButton33.setBorderPainted(false);
        jButton33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton33MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton33MouseExited(evt);
            }
        });
        mainPanel.add(jButton33);

        jButton24.setBackground(new java.awt.Color(249, 249, 249));
        jButton24.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton24.setText(",");
        jButton24.setBorder(null);
        jButton24.setBorderPainted(false);
        jButton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton24MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton24MouseExited(evt);
            }
        });
        mainPanel.add(jButton24);

        jButton21.setBackground(new java.awt.Color(236, 177, 142));
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-equal-sign-20.png"))); // NOI18N
        jButton21.setBorder(null);
        jButton21.setBorderPainted(false);
        jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton21MouseExited(evt);
            }
        });
        mainPanel.add(jButton21);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
            .addComponent(outputPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(outputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        jButton3.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        jButton3.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        jButton4.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        jButton4.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        jButton5.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        jButton5.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        jButton6.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        jButton6.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_jButton6MouseExited

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
        jButton7.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseExited
        jButton7.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_jButton7MouseExited

    private void jButton8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseEntered
        jButton8.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton8MouseEntered

    private void jButton8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseExited
        jButton8.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_jButton8MouseExited

    private void jButton17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseEntered
        jButton17.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton17MouseEntered

    private void jButton17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseExited
       jButton17.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_jButton17MouseExited

    private void jButton13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseEntered
        jButton13.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton13MouseEntered

    private void jButton13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseExited
        jButton13.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_jButton13MouseExited

    private void jButton9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseEntered
        jButton9.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton9MouseEntered

    private void jButton9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseExited
        jButton9.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_jButton9MouseExited

    private void jButton25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton25MouseEntered
        jButton25.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton25MouseEntered

    private void jButton25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton25MouseExited
        jButton25.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_jButton25MouseExited

    private void jButton18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseEntered
        jButton18.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton18MouseEntered

    private void jButton18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseExited
        jButton18.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_jButton18MouseExited

    private void jButton34MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton34MouseEntered
        jButton34.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton34MouseEntered

    private void jButton34MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton34MouseExited
        jButton34.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_jButton34MouseExited

    private void jButton32MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton32MouseEntered
        jButton32.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton32MouseEntered

    private void jButton32MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton32MouseExited
        jButton32.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_jButton32MouseExited

    private void jButton26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton26MouseEntered
        jButton26.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton26MouseEntered

    private void jButton26MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton26MouseExited
        jButton26.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_jButton26MouseExited

    private void jButton27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton27MouseEntered
        jButton27.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton27MouseEntered

    private void jButton27MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton27MouseExited
        jButton27.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_jButton27MouseExited

    private void jButton28MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton28MouseEntered
        jButton28.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton28MouseEntered

    private void jButton28MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton28MouseExited
        jButton28.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_jButton28MouseExited

    private void jButton29MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton29MouseEntered
        jButton29.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton29MouseEntered

    private void jButton29MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton29MouseExited
        jButton29.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_jButton29MouseExited

    private void jButton30MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton30MouseEntered
        jButton30.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton30MouseEntered

    private void jButton30MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton30MouseExited
        jButton30.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_jButton30MouseExited

    private void jButton31MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton31MouseEntered
        jButton31.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton31MouseEntered

    private void jButton31MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton31MouseExited
        jButton31.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_jButton31MouseExited

    private void jButton22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseEntered
        jButton22.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton22MouseEntered

    private void jButton22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseExited
        jButton22.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_jButton22MouseExited

    private void jButton33MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton33MouseEntered
        jButton33.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton33MouseEntered

    private void jButton33MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton33MouseExited
        jButton33.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_jButton33MouseExited

    private void jButton24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton24MouseEntered
        jButton24.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_jButton24MouseEntered

    private void jButton24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton24MouseExited
        jButton24.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_jButton24MouseExited

    private void jButton21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseEntered
        jButton21.setBackground(new java.awt.Color(241,138,77));
    }//GEN-LAST:event_jButton21MouseEntered

    private void jButton21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseExited
        jButton21.setBackground(new java.awt.Color(236,177,142));
    }//GEN-LAST:event_jButton21MouseExited

    private void clearMemoryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMemoryButtonMouseEntered
        if(clearMemoryButton.isEnabled()){
            clearMemoryButton.setBackground(new java.awt.Color(209,209,209));
            clearMemoryButton.setToolTipText("Clear all memory");
        }
    }//GEN-LAST:event_clearMemoryButtonMouseEntered

    private void clearMemoryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMemoryButtonMouseExited
        clearMemoryButton.setBackground(new java.awt.Color(230,230,230));
    }//GEN-LAST:event_clearMemoryButtonMouseExited

    private void recallMemoryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recallMemoryButtonMouseEntered
        if(recallMemoryButton.isEnabled()){
            recallMemoryButton.setBackground(new java.awt.Color(209,209,209));
            recallMemoryButton.setToolTipText("Memory recall");
        }
    }//GEN-LAST:event_recallMemoryButtonMouseEntered

    private void recallMemoryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recallMemoryButtonMouseExited
        recallMemoryButton.setBackground(new java.awt.Color(230,230,230));
    }//GEN-LAST:event_recallMemoryButtonMouseExited

    private void addMemoryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMemoryButtonMouseEntered
        addMemoryButton.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_addMemoryButtonMouseEntered

    private void addMemoryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMemoryButtonMouseExited
       addMemoryButton.setBackground(new java.awt.Color(230,230,230));
    }//GEN-LAST:event_addMemoryButtonMouseExited

    private void subtrackMemoryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtrackMemoryButtonMouseEntered
        subtrackMemoryButton.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_subtrackMemoryButtonMouseEntered

    private void subtrackMemoryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtrackMemoryButtonMouseExited
        subtrackMemoryButton.setBackground(new java.awt.Color(230,230,230));
    }//GEN-LAST:event_subtrackMemoryButtonMouseExited

    private void storeMemoryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storeMemoryButtonMouseEntered
        storeMemoryButton.setBackground(new java.awt.Color(209,209,209));
    }//GEN-LAST:event_storeMemoryButtonMouseEntered

    private void storeMemoryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storeMemoryButtonMouseExited
       storeMemoryButton.setBackground(new java.awt.Color(230,230,230));
    }//GEN-LAST:event_storeMemoryButtonMouseExited

    private void memoryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memoryButtonMouseEntered
       if(memoryButton.isEnabled()){
           memoryButton.setBackground(new java.awt.Color(209,209,209));
           memoryButton.setToolTipText("Memory");
       }
    }//GEN-LAST:event_memoryButtonMouseEntered

    private void memoryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memoryButtonMouseExited
        memoryButton.setBackground(new java.awt.Color(230,230,230));
    }//GEN-LAST:event_memoryButtonMouseExited

    private void addMemoryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMemoryButtonMouseClicked
        clearMemoryButton.setEnabled(true);
        recallMemoryButton.setEnabled(true);
        memoryButton.setEnabled(true);
    }//GEN-LAST:event_addMemoryButtonMouseClicked

    private void subtrackMemoryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtrackMemoryButtonMouseClicked
        clearMemoryButton.setEnabled(true);
        recallMemoryButton.setEnabled(true);
        memoryButton.setEnabled(true);
    }//GEN-LAST:event_subtrackMemoryButtonMouseClicked

    private void storeMemoryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storeMemoryButtonMouseClicked
        clearMemoryButton.setEnabled(true);
        recallMemoryButton.setEnabled(true);
        memoryButton.setEnabled(true);
    }//GEN-LAST:event_storeMemoryButtonMouseClicked

    private void clearMemoryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMemoryButtonMouseClicked
        if(clearMemoryButton.isEnabled()){
            clearMemoryButton.setEnabled(false);
            recallMemoryButton.setEnabled(false);
            memoryButton.setEnabled(false);
        }
    }//GEN-LAST:event_clearMemoryButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TopPanel;
    private javax.swing.JButton addMemoryButton;
    private javax.swing.JButton clearMemoryButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton memoryButton;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JButton recallMemoryButton;
    private javax.swing.JButton storeMemoryButton;
    private javax.swing.JButton subtrackMemoryButton;
    // End of variables declaration//GEN-END:variables
}
