/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.calculator_app;

/**
 *
 * @author konri
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        this.setTitle("Calculator");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        modelLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        outputPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(230, 230, 230));

        TopPanel.setBackground(new java.awt.Color(230, 230, 230));

        String mode = new String("\u2630").toUpperCase();
        modelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N
        modelLabel.setBounds(2, 6, 61, 37);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Standard");

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(modelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        outputPanel.setBackground(new java.awt.Color(230, 230, 230));

        javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
        outputPanel.setLayout(outputPanelLayout);
        outputPanelLayout.setHorizontalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        outputPanelLayout.setVerticalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        mainPanel.setBackground(new java.awt.Color(230, 230, 230));
        mainPanel.setLayout(new java.awt.GridLayout(6, 4, 2, 2));

        jButton1.setBackground(new java.awt.Color(240, 240, 240));
        jButton1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton1.setText("%");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        mainPanel.add(jButton1);

        jButton3.setBackground(new java.awt.Color(240, 240, 240));
        jButton3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton3.setText("CE");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        mainPanel.add(jButton3);

        jButton4.setBackground(new java.awt.Color(240, 240, 240));
        jButton4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton4.setText("C");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        mainPanel.add(jButton4);

        jButton5.setBackground(new java.awt.Color(240, 240, 240));
        jButton5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton5.setText("jButton1");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        mainPanel.add(jButton5);

        jButton6.setBackground(new java.awt.Color(240, 240, 240));
        jButton6.setText("jButton1");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        mainPanel.add(jButton6);

        jButton7.setBackground(new java.awt.Color(240, 240, 240));
        jButton7.setText("jButton1");
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        mainPanel.add(jButton7);

        jButton8.setBackground(new java.awt.Color(240, 240, 240));
        jButton8.setText("jButton1");
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        mainPanel.add(jButton8);

        jButton17.setBackground(new java.awt.Color(240, 240, 240));
        jButton17.setText("/");
        jButton17.setBorder(null);
        jButton17.setBorderPainted(false);
        mainPanel.add(jButton17);

        jButton18.setBackground(new java.awt.Color(249, 249, 249));
        jButton18.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton18.setForeground(new java.awt.Color(0, 0, 0));
        jButton18.setText("7");
        jButton18.setBorder(null);
        jButton18.setBorderPainted(false);
        mainPanel.add(jButton18);

        jButton34.setBackground(new java.awt.Color(249, 249, 249));
        jButton34.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton34.setForeground(new java.awt.Color(0, 0, 0));
        jButton34.setText("8");
        jButton34.setBorder(null);
        jButton34.setBorderPainted(false);
        mainPanel.add(jButton34);

        jButton32.setBackground(new java.awt.Color(249, 249, 249));
        jButton32.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton32.setForeground(new java.awt.Color(0, 0, 0));
        jButton32.setText("9");
        jButton32.setBorder(null);
        jButton32.setBorderPainted(false);
        mainPanel.add(jButton32);

        jButton13.setBackground(new java.awt.Color(240, 240, 240));
        jButton13.setText("*");
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        mainPanel.add(jButton13);

        jButton26.setBackground(new java.awt.Color(249, 249, 249));
        jButton26.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton26.setForeground(new java.awt.Color(0, 0, 0));
        jButton26.setText("4");
        jButton26.setBorder(null);
        jButton26.setBorderPainted(false);
        mainPanel.add(jButton26);

        jButton27.setBackground(new java.awt.Color(249, 249, 249));
        jButton27.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton27.setForeground(new java.awt.Color(0, 0, 0));
        jButton27.setText("5");
        jButton27.setBorder(null);
        jButton27.setBorderPainted(false);
        mainPanel.add(jButton27);

        jButton28.setBackground(new java.awt.Color(249, 249, 249));
        jButton28.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton28.setForeground(new java.awt.Color(0, 0, 0));
        jButton28.setText("6");
        jButton28.setBorder(null);
        jButton28.setBorderPainted(false);
        mainPanel.add(jButton28);

        jButton9.setBackground(new java.awt.Color(240, 240, 240));
        jButton9.setText("-");
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        mainPanel.add(jButton9);

        jButton29.setBackground(new java.awt.Color(249, 249, 249));
        jButton29.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton29.setForeground(new java.awt.Color(0, 0, 0));
        jButton29.setText("1");
        jButton29.setBorder(null);
        jButton29.setBorderPainted(false);
        mainPanel.add(jButton29);

        jButton30.setBackground(new java.awt.Color(249, 249, 249));
        jButton30.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton30.setForeground(new java.awt.Color(0, 0, 0));
        jButton30.setText("2");
        jButton30.setBorder(null);
        jButton30.setBorderPainted(false);
        mainPanel.add(jButton30);

        jButton31.setBackground(new java.awt.Color(249, 249, 249));
        jButton31.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton31.setForeground(new java.awt.Color(0, 0, 0));
        jButton31.setText("3");
        jButton31.setBorder(null);
        jButton31.setBorderPainted(false);
        mainPanel.add(jButton31);

        jButton25.setBackground(new java.awt.Color(240, 240, 240));
        jButton25.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jButton25.setText("+");
        jButton25.setBorder(null);
        jButton25.setBorderPainted(false);
        mainPanel.add(jButton25);

        jButton22.setBackground(new java.awt.Color(249, 249, 249));
        jButton22.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton22.setText("jButton1");
        jButton22.setBorder(null);
        jButton22.setBorderPainted(false);
        mainPanel.add(jButton22);

        jButton33.setBackground(new java.awt.Color(249, 249, 249));
        jButton33.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton33.setForeground(new java.awt.Color(0, 0, 0));
        jButton33.setText("0");
        jButton33.setBorder(null);
        jButton33.setBorderPainted(false);
        mainPanel.add(jButton33);

        jButton24.setBackground(new java.awt.Color(249, 249, 249));
        jButton24.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton24.setText(",");
        jButton24.setBorder(null);
        jButton24.setBorderPainted(false);
        mainPanel.add(jButton24);

        jButton21.setBackground(new java.awt.Color(236, 177, 142));
        jButton21.setText("jButton1");
        jButton21.setBorder(null);
        jButton21.setBorderPainted(false);
        mainPanel.add(jButton21);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addComponent(outputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(outputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TopPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JPanel outputPanel;
    // End of variables declaration//GEN-END:variables
}
